pipeline {
    agent any
    stages {
        stage('Verificar Repositório') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], useRemoteConfigs: [[url: 'https://github.com/ericknathan1/edificar-oficial']]])
            }
        }

        stage('Instalar Dependências') {
            steps {
                script {
                    // Atualiza o PATH se necessário
                    env.PATH = "/usr/bin:$PATH"
                    // Instalar as dependências Maven antes de compilar o projeto
                    bat 'mvn clean install'  // Instala as dependências do Maven
                }
            }
        }

        stage('Construir Imagem Docker') {
            steps {
                script {
                    def appName = 'edificar'
                    def imageTag = "${appName}:${env.BUILD_ID}"
                    dir('backend') {
                        // Construir a imagem Docker
                        bat "docker build -t ${imageTag} ."
                    }
                }
            }
        }

        stage('Fazer Deploy') {
            steps {
                script {
                    def appName = 'edificar'
                    def imageTag = "${appName}:${env.BUILD_ID}"

                    dir('backend') {
                        // Parar e remover o container existente
                        bat "docker stop ${appName} || exit 0"
                        bat "docker rm -v ${appName} || exit 0"
                    }


                    // Você parou e removeu o container, mas não iniciou o novo.
                    // Você precisa adicionar o comando 'docker run' aqui.
                    // Exemplo:
                    // bat "docker run -d --name ${appName} -p 8080:8080 ${imageTag}"
                }
            }
        }
    }
    post {
        success {
            echo 'Deploy realizado com sucesso!'
        }
        failure {
            echo 'Houve um erro durante o deploy.'
        }
    }
}

